### ISSUE TITLE
fix: circular dependency in downstream apps

### ISSUE THREAD

**Issue by adamdehaven** [nuxt-modules/sitemap#334] opened 2024-08-07 21:28 UTC
### 🐛 The bug

![image](https://github.com/user-attachments/assets/9ac9f638-db39-4653-9317-56982370e9cf)

### 🛠️ To reproduce

See links

### 🌈 Expected behavior

No circular dependency

### ℹ️ Additional context

I believe it was caused by https://github.com/nuxt-modules/sitemap/pull/319/files#diff-e46f77d6f08aafcb2ef2b76d269b0c95df5728426759e64d1ecff2b53ba1c2b9

**Comment by harlan-zw** [comment] 2024-08-16 11:37
Duplicate of https://github.com/nuxt-modules/sitemap/issues/340 (should be fixed in next release).

**Closed by harlan-zw** 2024-08-16 11:37 UTC
Labels: bug
